###
# EVENTS | CREATE NEW
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "New Event for delete test",
  "description": "This is a new event to delete test",
  "date": "2022-01-05T19:00:00",
  "price": 125.00
}

###
@eventId = {{ createEvent.response.body.id }}

###
# EVENTS | LIST ALL
GET http://localhost:3000/events
Content-Type: application/json

###
# EVENTS | GET BY ID
GET http://localhost:3000/events/bab6117a-0051-4457-ac4f-096ffdc3490c
Content-Type: application/json

###
# EVENTS | UPDATE
PATCH  http://localhost:3000/events/bab6117a-0051-4457-ac4f-096ffdc3490c
Content-Type: application/json

{
  "description": "This is a new great event",
  "date": "2022-01-05T19:00:00",  
  "price": 99.90
}

###
# EVENTS | DELETE
DELETE http://localhost:3000/events/f8e33da4-d27d-41a3-899c-00df629f62a0
Content-Type: application/json


###
@selectedEventId = 9528e5f0-bb3e-465d-802c-ce1f87d4c516

###
# SPOTS | CREATE
POST http://localhost:3000/events/{{selectedEventId}}/spots
Content-Type: application/json

{
  "name": "B6"
}

###
# SPOTS | LIST
GET http://localhost:3000/events/{{selectedEventId}}/spots
Content-Type: application/json

###
# EVENTS | RESERVE
POST http://localhost:3000/events/{{selectedEventId}}/reserve
Content-Type: application/json

{
  "spots": ["B5", "B6"],
  "ticket_kind": "full",
  "email": "john.doe@example.com"
}