###
@token = 4cfB8O0St3X5zDXLLehYPH8JoiRtKyq2ezsu7LVelrssmeM4UsEvb6Ivf45fPkhc

###
# EVENTS | CREATE NEW
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "New Event 5",
  "description": "This is the new event 5",
  "date": "2022-07-22T00:00:00",
  "price": 270
}

###
@eventId = {{ createEvent.response.body.id }}

###
# EVENTS | LIST ALL
GET http://localhost:3000/events
Content-Type: application/json

###
# EVENTS | GET BY ID
GET http://localhost:3000/events/bab6117a-0051-4457-ac4f-096ffdc3490c
Content-Type: application/json

###
# EVENTS | UPDATE
PATCH  http://localhost:3000/events/bab6117a-0051-4457-ac4f-096ffdc3490c
Content-Type: application/json

{
  "description": "This is a new great event",
  "date": "2022-01-05T19:00:00",  
  "price": 99.90
}

###
# EVENTS | DELETE
DELETE http://localhost:3000/events/ca2efba1-f591-403b-8a4c-a340d15621d1
Content-Type: application/json


###
@selectedEventId = 6e0fb2dd-2cbf-4cda-b497-87391a391e83

###
# SPOTS | CREATE
POST http://localhost:3000/events/{{selectedEventId}}/spots
Content-Type: application/json

{
  "name": "A4"
}

###
# SPOTS | LIST
GET http://localhost:3000/events/{{selectedEventId}}/spots
Content-Type: application/json

###
# EVENTS | RESERVE
POST http://localhost:3000/events/{{selectedEventId}}/reserve
Content-Type: application/json
X-Api-Token: {{token}}

{
  "spots": ["A1", "A2"],
  "ticket_kind": "full",
  "email": "john.doe@example.com"
}